## Basic Configuration

baseurl = "https://edwardcher.github.io/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Edwardcher Monreal"
title = "Edwardcher Monreal"

theme = "hugo-goa"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Edwardcher Monreal"
intro = "Security Consultant, IT Pragmatist and Avid Technologist"
description = "Edward has 15+ years experience in the IT industry and maintains an intrinsic passion for finding Pragmatic Technologies that composes to solve practical problems. He doesn't like to reinvent the wheel, but when he finds the wheel is broken or square he's not afraid to build a round one."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2016"

## Site Meta Settings
[params.meta]

## Social Accounts
[params.social]
github = "edwardcher"
linkedin = "edwardcher"
twitter = "mouselessmonk"
email = "edwardcher.monreal@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Edwardcher Monreal. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/index.html"
